import { QueryBuilderClassName } from './query-builder.interfaces';

export const cssMap: { [key in QueryBuilderClassName]: string } = {
  arrowIconButton: 'q-arrow-icon-button',
  arrowIcon: 'q-icon q-arrow-icon',
  removeIcon: 'q-icon q-remove-icon',
  addIcon: 'q-icon q-add-icon',
  removeButtonSize: '',
  switchControl: '',
  switchRow: '',
  button: 'q-button',
  buttonGroup: 'q-button-group',
  removeButton: 'q-remove-button',
  switchGroup: 'q-switch-group',
  switchLabel: 'q-switch-label',
  switchRadio: 'q-switch-radio',
  rightAlign: 'q-right-align',
  transition: 'q-transition',
  collapsed: 'q-collapsed',
  treeContainer: 'q-tree-container',
  tree: 'q-tree',
  row: 'q-row',
  connector: 'q-connector',
  rule: 'q-rule',
  ruleSet: 'q-ruleset',
  invalidRuleSet: 'q-invalid-ruleset',
  emptyWarning: 'q-empty-warning',
  fieldControl: 'q-field-control',
  fieldControlSize: 'q-control-size',
  entityControl: 'q-entity-control',
  entityControlSize: 'q-control-size',
  operatorControl: 'q-operator-control',
  operatorControlSize: 'q-control-size',
  inputControl: 'q-input-control',
  inputControlSize: 'q-control-size',
  'clear-dummy': '',
};
